### ISSUE TITLE
Need help with reading data from xDrip+

### ISSUE THREAD

**Issue by randytate** [tynbendad/GarminCIQ-NightscoutData#3]
I found your app on Garmin Connect today, and am super excited that you've implemented the "Data Field" option for seeing glucose data!  I have been using a [Widget](https://apps.garmin.com/en-US/apps/73115e04-dc9f-4765-ad88-e7ae283ce995) with xDrip, which is helpful, but requires many button clicks on my device to access while cycling.

But, I'm having trouble getting _NightscoutData_ Data Field to work with xDrip. I am looking for some help ... and also writing this issue as (hopefully) a guide for others trying to set this up.  Feel free to copy this guide into your github project as a README.md if you think it would help others.

## Prerequisites
* A Garmin Device (I have Garmin Edge 520)
* Garmin Connect Mobile App installed on mobile phone (Android for me)
* Phone paired with device via bluetooth
* CGM, such as Dexcom G5/G6
* xDrip app on phone, connected to CGM, and configured with:
  * Settings
  * Inter-app settings
  * xDrip Web Service = on

## NightscoutData Install
* Open Garmin Connect Mobile App on mobile device
* Garmin Devices
* (Select Device)
* Activities & App Management
* Data Fields
* Get More Data Fields
* Search for _NightscoutData_
  * Version 0.0.8 ... here's the link to it in the [Garmin Connect Store](https://apps.garmin.com/en-US/apps/2be02a1d-1d52-4db6-8bd5-6f66fe5ca992)
  * _Download_

## NightscoutData Configuration
* Open Garmin Connect Mobile app, if not already open
* Go to Device
* Activities & App Management
* Data Fields
* (You should see NightscoutData if installation was done correctly)
* Select NightscoutData

#### Settings

| Setting Name | Value |
| --- | --- |
| Nightscout site URL | *blank* (not using Nightscout) |
| Offline (local uploader) URL | `xdrip`  (also tried `xdrip+` |
| Display Mode | `e.g.: 141 5m -4 Down` |
| Title for data field | `xDrip` |

... click _Done_ after changing settings.

## Setup on Device (Garmin Edge 520)
* Added a field to an Activity Profile as follows:
  * Settings
  * Activity Profiles
  * (selected an existing profile)
  * Data Screens
  * Screen 1
  * Field 3
  * ConnectIQ
  * NightscoutData

## Start a Session on Garmin
* I see the field "xDrip" on the data screen, but no data
* I believe that the connection to xdrip is working, because I can access the [xDrip+ Widget](https://apps.garmin.com/en-US/apps/73115e04-dc9f-4765-ad88-e7ae283ce995) through the Status Page and see data that matches xDrip on my phone.

Any ideas?

(P.S. I would be happy to help you get your latest code into github to match the version available for download on Garmin Connect's site)

**Comment by tynbendad** [comment]
Hi, your instructions look correct to me - I'm not sure why they didn't
work. If the xdrip+ widget works, this should be able to work as well since
it uses the same local web server... sorry, I'm not sure what else you can
try; do let me know if you figure it out.
regards,
j

**Comment by randytate** [comment]
Tried again tonight.  After uninstalling some unused widgets, it started **working** (not sure if that is even related).

Thanks for building a very useful Garmin app for T1D athletes!

**Comment by PhilipeViana** [comment]
> Tried again tonight. After uninstalling some unused widgets, it started **working** (not sure if that is even related).
> 
> Thanks for building a very useful Garmin app for T1D athletes!

Hi Randy.


I am trying to connect Xdrip + to Garmin Edge 820 using the same parameters as you. The field is blank in Garmin as it happened to you.

In offline URL (local uploader):
You set
xdrip or xdrip +?

Did you make any changes to the settings you mentioned above?

**Comment by tynbendad** [comment]
Please see this issue: https://forums.garmin.com/developer/connect-iq/i/bug-reports/connect-version-4-20-broke-local-http-access

**Comment by alfkla** [comment]
Hi, I had simular problem with **xdrip+ app** apearing on my garmin watch, but not data received, only the following message: "**xDrip+ installed? Web Service enabled?**"
Now, when I started the Diabox app on my phone, cliced the settings gear icon on the bottom right, clicked intergration menu, and checked the boxes for "_share data with other apps_" and "_share data with smartwatches_". **It solved my problem**!
